import './globals.css';
import { Inter } from 'next/font/google';
import { LanguageProvider } from '../contexts/LenguageContext';
import { AuthProvider } from '../contexts/AuthProvider';
import ProtectRoute from '../components/ProtectRoute';

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Juego Cubilete</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body className={inter.className}>
        <LanguageProvider>
          <AuthProvider>
            <ProtectRoute>{children}</ProtectRoute>
          </AuthProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}



// import './globals.css'
// import { Inter } from 'next/font/google'
// // import { LanguageProvider } from '../contexts/LenguageContext';
// import { LanguageProvider } from '../contexts/LenguageContext';
// import { AuthProvider } from '../contexts/AuthContexts';

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Juego Cubilete',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <LanguageProvider>
//           {children}
//         </LanguageProvider>
//       </body>
//     </html>
//   )
// }
